### ISSUE TITLE
Enable viewing methods full documentation in the online documentation of CUQIpy

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#138]
Methods in the documentation is not clickable and their full documentation cannot be viewed. e.g. `plot_ci` in [Samples](https://cuqi-dtu.github.io/CUQIpy/api/_autosummary/cuqi.samples/cuqi.samples.Samples.html#cuqi.samples.Samples) documentation. The docstring for `plot_ci` has description of the parameters that does not show in the documentation.

**Comment by nabriis** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by amal-ghamdi** [comment]
😃👍
