### ISSUE TITLE
AffineModel (Old related SumOfModels and JointLinearModel)

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#146]
Add an AffineModel to CUQIpy. 

The other issue related to SumOfModels is closed. We will use RVs and algebra instead.

### Description
The `AffineModel` will define a forward operation based on the equation:

$$
x \rightarrow Ax + b
$$

where $A$ represents a linear operator, and $b$ is a shift or bias term.

### Implementation Details
The model should be initialized with an API in the form of:

    AffineModel(linear_operator, shift, linear_operator_adjoint, ...)

# DoD
- [x] AffineModel is implemented
- [x] LinearRTO and UGLA is updated to support AffineModel
- [x] Unit tests are added to AffineModel
- [x] Unit tests are added to LInearRTO and UGLA
- [x] Code is reviewed and approved

## Old issue:

Code from dev-alpha

```python
```python
class JointLinearModel:

    def __init__(self, models: List[LinearModel]):
        self.models = models
        self.shift = 0

    def __call__(self, **kwargs):
        # Create new JointLinearModel
        new_model = copy(self) # Shallow copy of self
        new_model.models = self.models[:] # Shallow copy of models in list

        # Go through each key
        for kwarg, value in kwargs.items():
            # Go through each model
            for model in new_model.models:
                #evaluate if kwarg matches _non_default_args
                if kwarg in get_non_default_args(model):
                    # make dict of kwarg and value
                    new_model.shift += model(value)
                    #new_model.shift += model(**{kwarg: value}) #Model needs to support this
                    
                    # Remove model from list
                    new_model.models.remove(model)

        if len(new_model.models) == 1:
            new_model.models[0].shift = new_model.shift
            return new_model.models[0]
        return new_model

    @property
    def _non_default_args(self):
        # Return non-default args of all models
        L = [get_non_default_args(model) for model in self.models]
        # Make a single list
        single_L = [item for sublist in L for item in sublist]
        # Combine list of lists into one list (no duplicates)
        return list(set(single_L))

    def __len__(self):
        return self.models[0].range_dim
```

For e.g. LinearRTO we would have to add the option of shifting the data, e.g. when the linear model is x -> Ax+shift.

```python
    @property
    def data(self):
        if hasattr(self.target.model, 'shift'):
            return self.target.data - self.target.model.shift
        return self.target.data
```

**Comment by nabriis** [comment]
@jakobsj DOD

**Comment by jakobsj** [comment]
@nabriis Approving DoD.  

I know this is an old issue - so going forward in general, for issues of new functionality/concepts (here the affine model), we should add a short explanation of what it is (for example with relevant formula) and how it is expected to be called, here in the issue. This will then be further refined and described by the text field of the PR with the actual implementation.

**Comment by nabriis** [comment]
@jakobsj updated in case you want to see the details.
