### ISSUE TITLE
Bugs in check of diagonal sqrtprec in gaussian 

### ISSUE THREAD

**Issue by siljachr** [CUQI-DTU/CUQIpy#181]
Fail 1:
There should be a check whether or not the sqrtprec is square. Currently, if it is not square, it fails.
Example:
N = 2
M = 3
x = cuqi.distribution.Gaussian(mean = np.zeros(N**2), sqrtprec = np.ones((M,N)))

Fail 2:
The diagonal matrix check is performed by extracting the diagonal of sqrtprec and forming a new, _dense_ matrix. This fails when the sqrtprec is high dimensional (and sparse) because there it allocates too much memory. 
Example:
N = 500
y = cuqi.distribution.Gaussian(mean = np.zeros(N**2), sqrtprec = sp.sparse.spdiags(np.ones(N**2), 0, N**2, N**2))

**Comment by Karl-JT** [comment]
Hi, I'm interested to contribute to this project. I think I fixed fail 2. 

For fail 1, would you like to have a warning?

**Comment by amal-ghamdi** [comment]
@nabriis was fail 1 addressed?
