### ISSUE TITLE
Rename Laplace_diff to LMRF, library, demos and paper notebooks

### ISSUE THREAD

**Issue by jakobsj** [CUQI-DTU/CUQIpy#231]
Note by @amal-ghamdi 

This update was implemented in CUQIpy library in PR #https://github.com/CUQI-DTU/CUQIpy/pull/229

in demos in PR #https://github.com/CUQI-DTU/CUQIpy-demos/pull/62

and in paper 1 notebook repository in PR #https://github.com/CUQI-DTU/Paper-CUQIpy-1-Core/pull/15

Also Laplace_diff is not used in paper 2.

**Comment by amal-ghamdi** [comment]
@jakobsj, @nabriis 

This issue was resolved in the merged PRs above. No need for code update here I believe. (changing status to in review)

**Comment by nabriis** [comment]
LGTM

**Comment by jakobsj** [comment]
Sounds good, please close.
