### ISSUE TITLE
Update Unadjusted Laplace Approx to UGLA in training and paper repo

### ISSUE THREAD

**Issue by jakobsj** [CUQI-DTU/CUQIpy#234]
Update of the paper repo done in: https://github.com/CUQI-DTU/Paper-CUQIpy-1-Core/pull/14 

Update of the training material done in: https://github.com/CUQI-DTU/CUQIpy-demos/pull/62

Update of CUQIpy done in: https://github.com/CUQI-DTU/CUQIpy/pull/217

**Comment by amal-ghamdi** [comment]
@jakobsj and @nabriis 

I think this issue can be closed without any code update. I added above the three PRs that implemented this change (I changed status to in review).

**Comment by nabriis** [comment]
LGTM

**Comment by jakobsj** [comment]
Sounds good.  Great that you have added the PRs that dealt with these, for future reference. Please close.
