### ISSUE TITLE
(Part I) Collect notebook from the Hackathon

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#294]
- [x] determine setup for displaying and keeping these notebooks (consider being available for participants in future training events)
- [x] collect notebooks from the team members
- [x] make sure they run/ add description

**Comment by nabriis** [comment]
Charlie added the following notebooks:
001_Besov_2D_deblurring (Andreas)
002_eigenvalue_forward (Felipe)
003_enhanced_error_model (Puyuan)
004_Besov_1D_deconvolution (Lara)
005_plug_and_play_prior (Remi)

Missing from:
- Aksel (Robin)
- Kristoffer (Helmholtz)
- Charlie (DA)
- Rafael (Mixture/Laplace)
- Jasper (Implicit Gaussian)
- Felipe (Horseshoe)
- Babak?
