### ISSUE TITLE
test NUTS checkpointing/state/history

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#404]
Description:
--------------
NUTS does not pass history, state and checkpointing tests. We want to fix this.

DoD:
------
- [x] Checkpointing, state, and history tests pass successfully for NUTS
- [x] Agreement on what constitutes state for NUTS is made (implied by the review and based on some discussions)
- [x] Any remaining issues (such as what is pointed out in the original description below) is delegated to other issues (comment by @amal-ghamdi: issue #537 is added and the test below is redundant I believe since we checked the checkpointing)
- [x] PR reviewed and merged

Original issue:
--------------

- Include testing case:
```
warmup(Ns)
warmup(Ns)
```
is equivalent to 
```
warmup(2*Ns)
```

Furthermore, consider getting rid of the _pre_warmup and _pre_sample methods. See Discussion in #408

**Comment by amal-ghamdi** [comment]
@jakobsj , can you check the DoD, please? Thanks!

**Comment by jakobsj** [comment]
@amal-ghamdi DoD approved!
