### ISSUE TITLE
Add method to display easy-to-read string for Samples object

### ISSUE THREAD

**Issue by taniagoia11** [CUQI-DTU/CUQIpy#468]
**Description**

when calling the function print on the array .sample(n>1) the output is
 `cuqi.samples._samples.Samples object at 0x0000013513CFA3C0`

It would be more useful to display some meaningful information, such as its dimension.

**Comment by chaozg** [comment]
Hi @taniagoia11 , thanks for raising this issue. I agree it might be more convenient if we display more custom information about the `Samples` object.
