### ISSUE TITLE
Tab completion of get_components

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#47]
I am not too happy with our get_components method of BayesianProblem. One major issue is that there is no tab completion on the get_components method because its a class_method and it needs the init parameters from the class.

Perhaps we can actually use the init of the BayesianProblem but add a property like

``` Python
A, y_obs, probInfo = Deconvolution1D.get_components(dim=50) # Old
A, y_obs, probInfo = Deconvolution1D(dim=50).model_data_info # New
```

This matches the python programming style and it also makes it more clear what the property does due to the name scheme. Finally it also opens up for other properties that could be accessed like that. For example

``` Python
A  = Deconvolution1D(dim=50).model # Only model
y_obs  = Deconvolution1D(dim=50).data # Only data
```
etc

Thoughts?

**Comment by nabriis** [comment]
@amal-ghamdi, @jakobsj

**Comment by amal-ghamdi** [comment]
That is a good point! I think something like you suggested is a very good idea (whether we add a method or property).

A variant of what you suggested: 
```
A, y_obs, probInfo = Deconvolution1D(dim=50).get_components()
```

**Comment by nabriis** [comment]
> That is a good point! I think something like you suggested is a very good idea (whether we add a method or property).
> 
> A variant of what you suggested:
> 
> ```
> A, y_obs, probInfo = Deconvolution1D(dim=50).get_components()
> ```

I kind of like the `get_components()` method. It could have keyword arguments (with defaults) such as `model=True`, `data=True`, `info=True`, etc.

**Comment by amal-ghamdi** [comment]
I think adding the kwargs works nicely!

**Comment by amal-ghamdi** [comment]
(comment from after hackathon)
get_components is very confusing (for example the following code returns the default phantom, 'sinc' and not the requested phantom 'square')
```
Deconvolution1D(phantom= 'square').get_components()
```
