### ISSUE TITLE
Documentation updates for training

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#470]
realted to #463
Description:
-------------
Go over CUQIpy documentation and make light updates to help improve the documentation (e.g. fixes of typos, equations not rendered correctly) and identify larger documentation update tasks that are necessary

Definition of done:
-------------------
- [x] Light update (as described above) is done, reviewed, and merged
- [ ] Bigger and necessary documentation update tasks are identified and corresponding issues are created, assigned and linked from this issue. (No major issues found at this stage.)
- [x] The possibility of fixing errors related to documentation that appear when CUQIpy is installed on a Windows machine is investigated
- [x] #488
- [x] Add experimental mcmc to main API page

Notes on Windows installation:
------------------------------
- @chaozg went through the CUQIpy installation process on Windows with Tania by following the instructions listed at the newest CUQIpy [documentation](https://cuqi-dtu.github.io/CUQIpy/user/getting_started.html), and everything worked fine. Just some notes:
  - After installation, it might take some time, like half a minute, for vscode to update its kernel options, so the just installed environment appears as an available python kernel
  - For working with the terminal interface in vscode, we should choose "terminal prompt" as the terminal type, as other terminals don't know conda

**Comment by chaozg** [comment]
Hi @jakobsj , the DoDs are ready for your review 😄

**Comment by jakobsj** [comment]
@chaozg looks good, maybe with the addition in item no 2 that new issues created are linked from this issue.

**Comment by chaozg** [comment]
Thanks @jakobsj , just updated item 2 according to your suggestion to "...corresponding issues are created, assigned and linked from this issue."
