### ISSUE TITLE
Dimension mismatch error for LinearModel with sample with 2D geometry

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQIpy#475]
When using a custom `LinearModel` from a matrix and a sample which has a 2D geometry, I meet a dimension mismatch error, though I'm not sure if it's due to a bug or my misuse of `LinearModel`. The following is a MWE:

```python
import cuqi
import numpy as np

my_matrix = np.random.rand(4,4)

my_model = cuqi.model.LinearModel(my_matrix,
                           domain_geometry=cuqi.geometry.Image2D((2,2)),
                           range_geometry=cuqi.geometry.Image2D((2,2)))

x = cuqi.distribution.Gaussian(mean=np.zeros(4),
                               cov=1.0,
                               geometry=cuqi.geometry.Image2D((2,2)))

my_model.forward(x.sample())
```

I expected that we could apply `my_model` on a sample from `x` with the last line above, but it gave the following error:
```bash
File ~/cuqi/model/_model.py:273, in Model._apply_func(self, func, func_range_geometry, func_domain_geometry, x, is_par, **kwargs)
    270 is_CUQIarray = type(x) is CUQIarray
    272 x = self._2fun(x, func_domain_geometry, is_par=is_par)
--> 273 out = func(x, **kwargs)
    275 # Return output as parameters 
    276 # (and wrapped in CUQIarray if input was CUQIarray)
...
--> 497         forward_func = lambda x: self._matrix@x
    498         adjoint_func = lambda y: self._matrix.T@y
    499         matrix = forward

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)
```

The suspicious line is `272 x = self._2fun(x, func_domain_geometry, is_par=is_par)` of `model/_model.py` where a vector (of size 4) is transformed to a matrix (of size 2x2). This leads to the dimension mismatch when the multiplication is performed at `line 497`.

I tried to comment out `line 272` and then everything worked as expected.

**Comment by nabriis** [comment]
This is because matrix assumes the input signal is a vector. If you provide a 2D image geometry you must either
1) use the visual_only argument in Image2D (then the geometry will not transform into image before applying A, or
2) use lamda functions to define forward and adjoint working on images. 

Hope that makes sense. The main reason is that geometries transform from parameter space to function value space before forward model is applied.

**Comment by chaozg** [comment]
Thank you, Nicolai! I didn't notice this `visual_only` option.
