### ISSUE TITLE
Acc rate not stored in HybridGibbs sampler

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#483]
**Description**

Currently the acceptance rate is not maintained in the HybridGibbs sampler. This means that tuning is not happening using the full acc rate of the chain.

## DoD:
- [x] HybridGibbs ensures samplers store acc rate while sampling
- [x] HybridGibbs maintains state and history of samplers
- [x] unit tests are implemented to check the above mentioned behavior

**Comment by jakobsj** [comment]
@nabriis can you add DoD here please?

**Comment by nabriis** [comment]
> @nabriis can you add DoD here please?

Done
