### ISSUE TITLE
Samplers accept invalid proposals

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQIpy#494]
**Description**

With a bounded prior, invalid proposals are accepted after a MH step. This happens to all samplers involving a MH step.

As seen in the following plot, an invalid proposal, negative here, is accepted after a MH step, which is not supposed to happen, and then the sampler gets stuck there.

**Example to reproduce**

```python
import cuqi
beta = cuqi.distribution.Beta(0.5, 0.5)
simpler = cuqi.sampler.MALA(beta, x0=0.1, scale=0.1)
simples = simpler.sample(1000, 0)
plt.plot(simples.samples.T[:10])
```
![bug](https://github.com/user-attachments/assets/06045a3c-d212-4c49-ab36-3236f74dc2e2)

# DoD
- [x] Identity the reason behind:
  - [x]  the validity of proposals is not checked at a MH step
- [ ] solution agreed by team and issue merged
  - [x] validate proposal with `isnan` and `isinf` at MH steps in relevant samplers, i.e., MH, CWMH, MALA, NUTS
- [x] proper test functions are created

**Comment by chaozg** [comment]
@nabriis , I just want to draw your attention to this issue since you were not at the standup when I briefly reported it.

**Comment by chaozg** [comment]
Hi @jakobsj  could you review the DoD here?

**Comment by jakobsj** [comment]
DoD approved!
