### ISSUE TITLE
Implement gradient for uniform distribution

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQIpy#495]
# Description
`cuqi.distribution.uniform` has no `grad`, and thus gradient-based samplers can't be used with it.

# DoD
- [x] Add `grad()` to `cuqi.distribution.Uniform`
- [x] ~~Add necessary unit tests~~ the correctness of gradient is already checked with the existing unit test, 
- [x] Test implementation with gradient-based sampler, i.e., MALA, ULA, NUTS
  - [x] test 1: draw from uniform distribution
  - [x] test 2: solve the simplest BIP
- [x] PR reviewed and merged to main

**Comment by chaozg** [comment]
Hi @jakobsj , could you please review the DoD here?

**Comment by jakobsj** [comment]
Thanks I'd say DoD here should include addition of a couple of meaningful unit tests.

**Comment by chaozg** [comment]
Thank you @jakobsj . I just added a bullet point on unit tests.

**Comment by jakobsj** [comment]
DoD approved
