### ISSUE TITLE
Provide more documentation details on experimental mcmc sampler module

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#514]
Description:
-------------
Update description of the experimental mcmc module to give more context and details.

Definition of done:
-------------------
- [x] Description of experimental mcmc module in API overview is updated
- [ ] Change is reviewed and accepted

**Comment by nabriis** [comment]
@jakobsj DoD

**Comment by jakobsj** [comment]
@nabriis DoD approved.
