### ISSUE TITLE
Add prefix to sampling progress

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#516]
Description:
-------------
Add prefix for warmup and sampling to samplers to more easily see what is going on with sampling. That is:

```bash
Warmup: [Progressbar]
Sample: [Progressbar]
```

More options could also be added in the future like acceptance rate etc. That requires a callback type thing to be handled. The prefix is easy and provides a lot of clarity

Definition of done:
-------------------
- [x] Pre-fix is implemented
- [x] Change is reviewed and accepted

**Comment by nabriis** [comment]
@jakobsj DOD
