### ISSUE TITLE
Update documentation github action to save artifacts

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#517]
Description:
-------------
To enable the developer to see the created CUQIpy documentation after each update to a PR, the created CUQIpy documentation can be uploaded and accessed through the github action interface. (see for example this CUQIpy documentation artifacts https://github.com/CUQI-DTU/CUQIpy/actions/runs/11869024631).

DoD:
------
- [x] Update docs.yml file to add artifact upload section (we have similar setup in CUQI-Book added by @nabriis )
- [ ] Decide if documentation build time is still acceptable (4min of increased docs build time is noticed, from 12min docs build time to about 16 min)
- [x] Get the update reviewed and approved

**Comment by amal-ghamdi** [comment]
@nabriis fyi, keeping track of this

**Comment by amal-ghamdi** [comment]
@jakobsj , can you please review the DoD. Thank you.

**Comment by jakobsj** [comment]
@amal-ghamdi DoD approved!
