### ISSUE TITLE
Warning in NUTS sampler for _epsilon_bar

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#524]
**Description**
The line of code, below, in NUTS is repeated twice and it generates a warning, we want to fix the line to get rid of the warning.
```python
if self._epsilon_bar == "unset": # Initial value of epsilon_bar for sampling
```
The warning:
```
/Users/amal/Documents/research_code/CUQI-DTU/CUQIpy/cuqi/experimental/mcmc/_hmc.py:315: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._epsilon_bar == "unset": # Initial value of epsilon_bar for sampling
```

**Example to reproduce**

See FENIcs notebook in CUQI book.
https://github.com/CUQI-DTU/CUQI-Book/pull/74/files#diff-65b82e897cf4d25e53f93d35bcc5f582f2a6ebc08a631af478f5546e7e591fd5

**Related online discussion of this warning**
https://stackoverflow.com/questions/40659212/futurewarning-elementwise-comparison-failed-returning-scalar-but-in-the-futur

DoD
-----
- [x] Fix to get rid of the warning is implemented
- [ ] Fix is reviewed and merged
- [ ] Issue created for CUQI-Book to rerun the notebooks that display this warning

**Comment by amal-ghamdi** [comment]
Can you please review the DoD @jakobsj? Thanks!

**Comment by jakobsj** [comment]
DoD approved @amal-ghamdi
