### ISSUE TITLE
Add a demo for the truncated Normal

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#546]
## DoD

- [x] Demo 1 of using gradient-based samplers to draw samples from a truncated normal distribution
- [x] Demo 2 of using gradient-based samplers to solve the simplest BIP problem with a truncated normal distribution as prior

**Comment by chaozg** [comment]
Hi @jakobsj, could you review the DoD here?

**Comment by jakobsj** [comment]
I'd like more details on how many (one combined or multiple shorter) notebooks are planned, which and the size of problem(s) to solve, which aspects to cover or leave out. As is, unclear if this is a massive task or a fairly small one. We discussed to complete it within this week as most of the notebook(s) had already been done, so I'd expect it is a smaller task, but please clarify, thanks!

**Comment by chaozg** [comment]
Hi @jakobsj , I was aiming at two demos at any given (bounded) prior: one for drawing samples and one for solving the simplest BIP. Just updated DoD to reflect this. Could you please help review it again?

**Comment by jakobsj** [comment]
@chaozg Thank you, DoD approved!

**Comment by chaozg** [comment]
Hi @jakobsj Could you please help review the DoD here? Instead of testing all bounded priors, which is too ambitious as some priors don't have `gradient()` yet, the focus of this issue is narrowed to only demonstrate the use of the truncated normal distribution.

**Comment by jakobsj** [comment]
@chaozg DoD approved  (though I would call it one demo with two parts, rather than two demos).

**Comment by amal-ghamdi** [comment]
@chaozg , I am closing this issue :)
