### ISSUE TITLE
Add gradient to normal

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQIpy#548]
##DoD:
- [x] Add gradient() to normal distribution
- [x] Add proper unit tests
- [ ] PR reviewed by team and merged to main

**Comment by chaozg** [comment]
@jakobsj In order to adapt the suggestion from review in PR #542 , we need to add gradient() to Normal distribution. Could you help review the DoD here?

**Comment by jakobsj** [comment]
@chaozg Thanks, DoD approved!
