### ISSUE TITLE
Can we make linear model with 2D Image geometry more intuitive

### ISSUE THREAD

**Issue by amal-ghamdi** [CUQI-DTU/CUQIpy#551]
Description:
------------
As suggested by @chaozg, it seems to be a recurring issue with users to find the right setting for 2D geometry when working with linear models (in particular setting the flag "visual_only")

There is a need to clear some confusion the user might encounter when preparing their forward model: If their forward model works on 2D images, they probably need `visual_only=False` (the default) when defining the domain geometry, and they probably need `visual_only=True` when the model works on vectors.

DoD
-----
- [x] A solution is found to make this setup more intuitive to the user.
    - It is decided to add a how-to to demonstrate/differentiate the use of Image2D
- [x] In a how-to file, demonstrate when `visual_only` is used and when it is not. 
    - The how-to should be concise and the examples should be intuitive.
    - The effect of using `visual_only` should be properly demonstrated and documented.
- [ ] Guide the user to the how-to file by putting links at the following places
    - Docstring of Model
    - Docstring of Image2D
    - Docstring of CUQI array and CUQI sample
- [ ] The solution is reviewed and approved

**Comment by amal-ghamdi** [comment]
fyi @jakobsj, @chaozg and @nabriis , issue is created

**Comment by chaozg** [comment]
Hi @jakobsj, could you please help review the DoD here?

**Comment by jakobsj** [comment]
@chaozg I think you suggested in a recent meeting to add some more details on this issue and I think it is a good idea to do this, before revieving the DoD.  

So it would be great if you could add something on: what is the confusion, ie short examples of how the code is to be used, how a user might expect it instead and initial proposed suggestion(s) for how to make the behaviour more intuitive.

**Comment by chaozg** [comment]
Hi @jakobsj, could you please review the DoD here since it was updated a bit after our stand-up?

**Comment by jakobsj** [comment]
@chaozg A howto seems a useful solution to help guide the user. My only comment is how we make sure the user is made aware of this howto in their workflow when they face the challenges of understanding Image2D. Would it be suitable to refer the user to the howto in the documentation/docstring of Image2D geometry? Are there other places a user might look for help during that situation and where we could add a link or similar?  Please can you think of good way(s) and update the DoD and PR accordingly.

**Comment by chaozg** [comment]
Thank you @jakobsj: that's a very nice suggestion. I agree it would be useful to add a link to the how-to file at the docstrings of relevant CUQI classes. For now, CUQI model, array and sample are in my mind.
