### ISSUE TITLE
Regularized Gaussian: TV

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#575]
Add Total Variation regularization as option to the regularized Gaussian distribution.

- [x] Total Variation ("tv") option with RegularizedGaussian and its variants. (1D and anisotropic 2D, depending on passed geometry)
- [x] Conditioning on the strength parameter for RegularizedGaussian (for future use with Gibbs)
- [x] Unit tests for conditioning added
- [x] Reviewed

**Comment by nabriis** [comment]
@jakobsj  DoD

**Comment by jakobsj** [comment]
@nabriis For DoD my only question is that only conditioning tests are mentioned, I would think it makes sense to add some unit tests on the added tv functionality aside from conditioning?

**Comment by jeverink** [comment]
> @nabriis For DoD my only question is that only conditioning tests are mentioned, I would think it makes sense to add some unit tests on the added tv functionality aside from conditioning?

To quote myself from #564 
> Regarding tests: I propose adding a small regression test of a full hierarchical model with a TV regularized model as part of the next PR, as many smaller things might change rapidly in future smaller PRs on the Regularized Gaussian Distribution.
