### ISSUE TITLE
RV: Variable class with algebra (using AST)

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#576]
Implement a variable class that can "record" various operations applied to it and allow this information to be used later. For example:
```python
x = Variable()
z = (x+2)**2
```
The variable `z` should know of the operations applied and it should be possible to apply them again to specific values of `x`, say `z(x=1)` should return the value 9.

- [x] Implement abstract syntax tree for a basic variable "node" class
- [x] Support core mathematical operations like (0, -, /, *)
- [x] Support mathematical operations: (abs, pow, neg, matmul)
- [x] Support operations: (getitem)
- [x] Implement repr for displaying operations applied to variable
- [x] Unit tests
- [x] Howto

**Comment by nabriis** [comment]
@jakobsj DoD

**Comment by jakobsj** [comment]
@nabriis looks good - I see a howto is added in the PR along with tests of algebra. Please add to DoD separate items for the howto and for unit tests (apart from testing algebra is it possible to add tests of the variable/node implementations)

**Comment by nabriis** [comment]
As we discussed if we want stuff like "I remembered to add unit tests" tickbox I want a template to use.

**Comment by jakobsj** [comment]
@nabriis Thanks for adding unit tests and howto in the specific DoD here so we can progress this issue. Yes absolutely unit tests will be part of the general template. DoD approved.
