### ISSUE TITLE
RV: "Basic" Random Variable class

### ISSUE THREAD

**Issue by nabriis** [CUQI-DTU/CUQIpy#577]
Implement a "basic" random variable class with the following features:
- [x] Support for variable algebra via #576 
- [x] Support for basic stochastic elements: Knowledge of distribution
- [x] Repr showing random variable
- [x] Basic distribution related attributes like "dim, geometry"
- [x] Name attribute as with Distributions
- [x] Can be used as "drop-in" replacement of lambda function in Bayesian model
- [x] Ensure unused keywords are caught and throw and error (from discussion in https://github.com/CUQI-DTU/CUQIpy/pull/583)
- [ ] After implementation, ensure variables classes are not exposed publically to users (also from https://github.com/CUQI-DTU/CUQIpy/pull/583)
- [x] Unit testss
- [x] Updated howto

For example one should be able to do as follows:
```python
A = LinearModel(...)
s = RandomVariable(Gamma(1, 1e-4))
x = RandomVariable(Gaussian(np.zeros(128), 1))
y = RandomVariable(Gaussian(A@x, 1/s)
joint = JointDistribution(x, y)
```
For now, let us allow JointDistribution to accept a both Distribution or RandomVariable as input, then internally extract the Distribution from the RandomVariable to keep the remainder of the flow in CUQIpy the same.

Later tasks will incorporate RandomVariables more directly.

**Comment by nabriis** [comment]
@jakobsj DoD

**Comment by jakobsj** [comment]
@nabriis DoD approved!
