### ISSUE TITLE
Better documentation/interface on RestorationPrior

### ISSUE THREAD

**Issue by chaozg** [CUQI-DTU/CUQIpy#588]
## Issue
- With the current implementation of `RestorationPrior`, we expect the user-supplied `restorator` to return a tuple of two variables, i.e., the "restored" solution and extra information.
- It's quite easy for the user (and us...) to make a mistake here as they might provide a function that only returns the "restored" solution when there is no meaningful extra information to provide. Particularly in a 2D case, we won't even notice this error as the code runs with such an incorrectly defined restorator (but gives wrong results, of course).

## DoD
- [x] Propose a solution and discuss it with team
  - Option 1: CUQIpy internally detects and handles no matter if the user-supplied restorator returns a solution or a tuple
  - Option 2: CUQIpy accepts only a function that returns a tuple of length 2 and raises error if it doesn't
  - Stand-up suggests that option 1 might add confusion to the user and we go with option 2
- [x] Investigate the use of `inspect` module to infer the return type of a user-supplied restorator
  - `inspect` seems not what we want here and we shouldn't expect our user to annotate their functions 
- [x] Check return type at run time and raise value error if the supplied restorator doesn't return a tuple of length 2.
- [x] Add unit test to check of the value error is correctly catpured
- [x] Update the docstring of `RestorationPrior` class, the `restore` method and ValueError message to guide the user.

**Comment by chaozg** [comment]
@jakobsj Could you please review the DoD here? It's intended to make the interface of `restorator` more robust to avoid mistakes (that are very easy to make).

**Comment by jakobsj** [comment]
@chaozg Thank you, could you explain why one may want to return such extra information as a second output and ideally point me to one or more specific examples of "extra information"?   Just considering whether it could be removed altogether such that always a single output is returned.

**Comment by chaozg** [comment]
@jakobsj I just updated the DoD here a bit after suggestions from our stand-up

**Comment by jakobsj** [comment]
@chaozg would it make sense to add a unit test checking that returning different number of outputs than 2 is caught? If so, please add a tickbox for unit test in the DoD.

**Comment by chaozg** [comment]
Thank you @jakobsj just update the DoD and the PR as you suggested.

**Comment by jakobsj** [comment]
THanks @chaozg DoD approved!
